version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: northwind_bi_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: northwind
    ports:
      - "5433:5432"
    volumes:
      # Map init scripts. Postgres executes them in alphabetical order.
      - ./sql/northwind.sql:/docker-entrypoint-initdb.d/00_northwind.sql
      - ./sql/01_star_schema.sql:/docker-entrypoint-initdb.d/01_star_schema.sql
      - ./sql/02_migration.sql:/docker-entrypoint-initdb.d/02_migration.sql
    restart: unless-stopped
